/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_example_codecdemo_JNIWrapper */

#ifndef _Included_com_example_codecdemo_JNIWrapper
#define _Included_com_example_codecdemo_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif




JNIEXPORT void JNICALL Java_com_example_codecdemo_JNIWrapper_initCodec
  (JNIEnv *, jclass );

JNIEXPORT void JNICALL Java_com_example_codecdemo_JNIWrapper_deInitCodec
  (JNIEnv *, jclass);

JNIEXPORT jbyteArray JNICALL Java_com_example_codecdemo_JNIWrapper_encodeOpus
(JNIEnv *, jclass , jshortArray );

JNIEXPORT jshortArray JNICALL Java_com_example_codecdemo_JNIWrapper_decodeOpus
(JNIEnv *, jclass , jbyteArray,int);

#ifdef __cplusplus
}
#endif
#endif





